"""init1

Revision ID: 6af41ba092c3
Revises: 3faeba03ada2
Create Date: 2023-07-24 19:23:23.950164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af41ba092c3'
down_revision = '3faeba03ada2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_blocked_tokes_id'), 'blocked_tokes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_blocked_tokes_id'), 'blocked_tokes', type_='unique')
    # ### end Alembic commands ###
